# Generated by Django 3.2.7 on 2023-01-07 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=2000)),
                ('lastName', models.CharField(max_length=2000)),
                ('userName', models.CharField(max_length=2000)),
                ('password', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('mobileNumber', models.CharField(max_length=20)),
                ('createdOn', models.DateTimeField(default=datetime.datetime(2023, 1, 7, 11, 16, 37, 949574))),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
