# Generated by Django 3.2.7 on 2023-01-07 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachDayMealTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('mealName', models.CharField(max_length=2000)),
                ('caloriesInTaken', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=2000)),
                ('mealPlanName', models.CharField(max_length=2000)),
                ('perDayCalories', models.CharField(max_length=2000)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='createdOn',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 7, 14, 46, 20, 427482)),
        ),
    ]
